### ISSUE TITLE
SerialChart.exe启动报错：无法找到入口

### ISSUE THREAD

**Issue by Jzjerry** [peng-zhihui/SerialChart#2]
使用环境：Windows 10 家庭版 20H2
下载了release里的zip后解压之后直接打开exe的时候报错无法启动了
内容：
无法定位程序输入点 __gxx_personality_v0 于动态链接库 (解压目录)/Qt5Core.dll 上。
![image](https://user-images.githubusercontent.com/20167827/119298879-7c339580-bc90-11eb-8193-6ed2b9bdda4d.png)

**Comment by peng-zhihui** [comment]
更新了，再试一下

**Comment by Jzjerry** [comment]
![image](https://user-images.githubusercontent.com/20167827/119299839-4becf680-bc92-11eb-8c92-d6be00d5bc43.png)
现在报这个了

**Comment by peng-zhihui** [comment]
现在呢，再试一下

**Comment by Jzjerry** [comment]
> 现在呢，再试一下

可以打开了！感谢QWQ
