### ISSUE TITLE
Qt5WebKit is deprecated

### ISSUE THREAD

**Issue by BisonLeo** [peng-zhihui/SerialChart#3]
Where is Qt5WebKit used in this project? Can we directly change it to Qt5WebEngine? 
or
Could you please provide the download link of Qt5 version that has Qt5Webkit?

**Comment by peng-zhihui** [comment]
use Qt version under 5.5.1 will be no problem



发自我的iPhone


------------------ Original ------------------
From: BisonLeo ***@***.***&gt;
Date: Fri,May 28,2021 7:26 PM
To: peng-zhihui/SerialChart ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [peng-zhihui/SerialChart] Qt5WebKit is deprecated (#3)





 
Where is Qt5WebKit used in this project? Can we directly change it to Qt5WebEngine?
 or
 Could you please provide the download link of Qt5 version that has Qt5Webkit?

**Comment by BisonLeo** [comment]
https://download.qt.io/new_archive/qt/5.5/5.5.1/
